/*
 * This file is generated by jOOQ.
 */
package com.acme.videorental.sharedKernel.infrastructure.jooq;


import com.acme.videorental.sharedKernel.infrastructure.jooq.tables.Film;
import com.acme.videorental.sharedKernel.infrastructure.jooq.tables.Customer;
import com.acme.videorental.sharedKernel.infrastructure.jooq.tables.FilmTransaction;
import com.acme.videorental.sharedKernel.infrastructure.jooq.tables.PaymentTransaction;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PRIMARY_KEY_5 = Indexes0.PRIMARY_KEY_5;
    public static final Index PRIMARY_KEY_2 = Indexes0.PRIMARY_KEY_2;
    public static final Index FK_CUSTOMER_ID_FILM_TRANSACTION_INDEX_F = Indexes0.FK_CUSTOMER_ID_FILM_TRANSACTION_INDEX_F;
    public static final Index FK_FILM_ID_FILM_TRANSACTION_INDEX_F = Indexes0.FK_FILM_ID_FILM_TRANSACTION_INDEX_F;
    public static final Index PRIMARY_KEY_F = Indexes0.PRIMARY_KEY_F;
    public static final Index FK_CUSTOMER_ID_PAYMENT_TRANSACTION_INDEX_3 = Indexes0.FK_CUSTOMER_ID_PAYMENT_TRANSACTION_INDEX_3;
    public static final Index PRIMARY_KEY_3 = Indexes0.PRIMARY_KEY_3;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PRIMARY_KEY_5 = Internal.createIndex("PRIMARY_KEY_5", Customer.CUSTOMER, new OrderField[] { Customer.CUSTOMER.CUSTOMER_ID }, true);
        public static Index PRIMARY_KEY_2 = Internal.createIndex("PRIMARY_KEY_2", Film.FILM, new OrderField[] { Film.FILM.FILM_ID }, true);
        public static Index FK_CUSTOMER_ID_FILM_TRANSACTION_INDEX_F = Internal.createIndex("FK_CUSTOMER_ID_FILM_TRANSACTION_INDEX_F", FilmTransaction.FILM_TRANSACTION, new OrderField[] { FilmTransaction.FILM_TRANSACTION.CUSTOMER_ID }, false);
        public static Index FK_FILM_ID_FILM_TRANSACTION_INDEX_F = Internal.createIndex("FK_FILM_ID_FILM_TRANSACTION_INDEX_F", FilmTransaction.FILM_TRANSACTION, new OrderField[] { FilmTransaction.FILM_TRANSACTION.FILM_ID }, false);
        public static Index PRIMARY_KEY_F = Internal.createIndex("PRIMARY_KEY_F", FilmTransaction.FILM_TRANSACTION, new OrderField[] { FilmTransaction.FILM_TRANSACTION.FILM_TRANSACTION_ID }, true);
        public static Index FK_CUSTOMER_ID_PAYMENT_TRANSACTION_INDEX_3 = Internal.createIndex("FK_CUSTOMER_ID_PAYMENT_TRANSACTION_INDEX_3", PaymentTransaction.PAYMENT_TRANSACTION, new OrderField[] { PaymentTransaction.PAYMENT_TRANSACTION.CUSTOMER_ID }, false);
        public static Index PRIMARY_KEY_3 = Internal.createIndex("PRIMARY_KEY_3", PaymentTransaction.PAYMENT_TRANSACTION, new OrderField[] { PaymentTransaction.PAYMENT_TRANSACTION.PAYMENT_TRANSACTION_ID }, true);
    }
}
