/*
 * This file is generated by jOOQ.
 */
package com.acme.videorental.sharedKernel.infrastructure.jooq;


import com.acme.videorental.sharedKernel.infrastructure.jooq.tables.Film;
import com.acme.videorental.sharedKernel.infrastructure.jooq.tables.Customer;
import com.acme.videorental.sharedKernel.infrastructure.jooq.tables.FilmTransaction;
import com.acme.videorental.sharedKernel.infrastructure.jooq.tables.PaymentTransaction;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1150738668;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.CUSTOMER</code>.
     */
    public final Customer CUSTOMER = Customer.CUSTOMER;

    /**
     * The table <code>PUBLIC.FILM</code>.
     */
    public final Film FILM = Film.FILM;

    /**
     * The table <code>PUBLIC.FILM_TRANSACTION</code>.
     */
    public final FilmTransaction FILM_TRANSACTION = FilmTransaction.FILM_TRANSACTION;

    /**
     * The table <code>PUBLIC.PAYMENT_TRANSACTION</code>.
     */
    public final PaymentTransaction PAYMENT_TRANSACTION = PaymentTransaction.PAYMENT_TRANSACTION;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Customer.CUSTOMER,
            Film.FILM,
            FilmTransaction.FILM_TRANSACTION,
            PaymentTransaction.PAYMENT_TRANSACTION);
    }
}
