/*
 * This file is generated by jOOQ.
 */
package com.casumo.videorental.infrastructure.repository.jooq;


import com.casumo.videorental.infrastructure.repository.jooq.tables.Customer;
import com.casumo.videorental.infrastructure.repository.jooq.tables.Film;
import com.casumo.videorental.infrastructure.repository.jooq.tables.FilmTransaction;
import com.casumo.videorental.infrastructure.repository.jooq.tables.PaymentTransaction;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.CUSTOMER</code>.
     */
    public static final Customer CUSTOMER = com.casumo.videorental.infrastructure.repository.jooq.tables.Customer.CUSTOMER;

    /**
     * The table <code>PUBLIC.FILM</code>.
     */
    public static final Film FILM = com.casumo.videorental.infrastructure.repository.jooq.tables.Film.FILM;

    /**
     * The table <code>PUBLIC.FILM_TRANSACTION</code>.
     */
    public static final FilmTransaction FILM_TRANSACTION = com.casumo.videorental.infrastructure.repository.jooq.tables.FilmTransaction.FILM_TRANSACTION;

    /**
     * The table <code>PUBLIC.PAYMENT_TRANSACTION</code>.
     */
    public static final PaymentTransaction PAYMENT_TRANSACTION = com.casumo.videorental.infrastructure.repository.jooq.tables.PaymentTransaction.PAYMENT_TRANSACTION;
}
