/*
 * This file is generated by jOOQ.
 */
package com.acme.videorental.sharedKernel.infrastructure.jooq.tables.records;


import com.acme.videorental.sharedKernel.infrastructure.jooq.tables.PaymentTransaction;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PaymentTransactionRecord extends UpdatableRecordImpl<PaymentTransactionRecord> implements Record5<String, String, Long, String, Timestamp> {

    private static final long serialVersionUID = -863148171;

    /**
     * Setter for <code>PUBLIC.PAYMENT_TRANSACTION.PAYMENT_TRANSACTION_ID</code>.
     */
    public void setPaymentTransactionId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.PAYMENT_TRANSACTION.PAYMENT_TRANSACTION_ID</code>.
     */
    public String getPaymentTransactionId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>PUBLIC.PAYMENT_TRANSACTION.CUSTOMER_ID</code>.
     */
    public void setCustomerId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.PAYMENT_TRANSACTION.CUSTOMER_ID</code>.
     */
    public String getCustomerId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.PAYMENT_TRANSACTION.AMOUNT</code>.
     */
    public void setAmount(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.PAYMENT_TRANSACTION.AMOUNT</code>.
     */
    public Long getAmount() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>PUBLIC.PAYMENT_TRANSACTION.PAYMENT_TYPE</code>.
     */
    public void setPaymentType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.PAYMENT_TRANSACTION.PAYMENT_TYPE</code>.
     */
    public String getPaymentType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.PAYMENT_TRANSACTION.CREATED_ON</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.PAYMENT_TRANSACTION.CREATED_ON</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, Long, String, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, Long, String, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return PaymentTransaction.PAYMENT_TRANSACTION.PAYMENT_TRANSACTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return PaymentTransaction.PAYMENT_TRANSACTION.CUSTOMER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return PaymentTransaction.PAYMENT_TRANSACTION.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return PaymentTransaction.PAYMENT_TRANSACTION.PAYMENT_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return PaymentTransaction.PAYMENT_TRANSACTION.CREATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getPaymentTransactionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCustomerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getPaymentType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getPaymentTransactionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCustomerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPaymentType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentTransactionRecord value1(String value) {
        setPaymentTransactionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentTransactionRecord value2(String value) {
        setCustomerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentTransactionRecord value3(Long value) {
        setAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentTransactionRecord value4(String value) {
        setPaymentType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentTransactionRecord value5(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentTransactionRecord values(String value1, String value2, Long value3, String value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PaymentTransactionRecord
     */
    public PaymentTransactionRecord() {
        super(PaymentTransaction.PAYMENT_TRANSACTION);
    }

    /**
     * Create a detached, initialised PaymentTransactionRecord
     */
    public PaymentTransactionRecord(String paymentTransactionId, String customerId, Long amount, String paymentType, Timestamp createdOn) {
        super(PaymentTransaction.PAYMENT_TRANSACTION);

        set(0, paymentTransactionId);
        set(1, customerId);
        set(2, amount);
        set(3, paymentType);
        set(4, createdOn);
    }
}
