/*
 * This file is generated by jOOQ.
 */
package com.casumo.videorental.infrastructure.repository.jooq.tables.records;


import com.casumo.videorental.infrastructure.repository.jooq.tables.FilmTransaction;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FilmTransactionRecord extends UpdatableRecordImpl<FilmTransactionRecord> implements Record6<String, String, String, Integer, String, Timestamp> {

    private static final long serialVersionUID = -111801144;

    /**
     * Setter for <code>PUBLIC.FILM_TRANSACTION.FILM_TRANSACTION_ID</code>.
     */
    public void setFilmTransactionId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.FILM_TRANSACTION.FILM_TRANSACTION_ID</code>.
     */
    public String getFilmTransactionId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>PUBLIC.FILM_TRANSACTION.FILM_ID</code>.
     */
    public void setFilmId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.FILM_TRANSACTION.FILM_ID</code>.
     */
    public String getFilmId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.FILM_TRANSACTION.CUSTOMER_ID</code>.
     */
    public void setCustomerId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.FILM_TRANSACTION.CUSTOMER_ID</code>.
     */
    public String getCustomerId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.FILM_TRANSACTION.NUM_DAYS</code>.
     */
    public void setNumDays(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.FILM_TRANSACTION.NUM_DAYS</code>.
     */
    public Integer getNumDays() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>PUBLIC.FILM_TRANSACTION.ACTION</code>.
     */
    public void setAction(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.FILM_TRANSACTION.ACTION</code>.
     */
    public String getAction() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PUBLIC.FILM_TRANSACTION.CREATED_ON</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.FILM_TRANSACTION.CREATED_ON</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, Integer, String, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, Integer, String, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return FilmTransaction.FILM_TRANSACTION.FILM_TRANSACTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return FilmTransaction.FILM_TRANSACTION.FILM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return FilmTransaction.FILM_TRANSACTION.CUSTOMER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return FilmTransaction.FILM_TRANSACTION.NUM_DAYS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return FilmTransaction.FILM_TRANSACTION.ACTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return FilmTransaction.FILM_TRANSACTION.CREATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getFilmTransactionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getFilmId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCustomerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getNumDays();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getAction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getFilmTransactionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFilmId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCustomerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getNumDays();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getAction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FilmTransactionRecord value1(String value) {
        setFilmTransactionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FilmTransactionRecord value2(String value) {
        setFilmId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FilmTransactionRecord value3(String value) {
        setCustomerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FilmTransactionRecord value4(Integer value) {
        setNumDays(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FilmTransactionRecord value5(String value) {
        setAction(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FilmTransactionRecord value6(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FilmTransactionRecord values(String value1, String value2, String value3, Integer value4, String value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FilmTransactionRecord
     */
    public FilmTransactionRecord() {
        super(FilmTransaction.FILM_TRANSACTION);
    }

    /**
     * Create a detached, initialised FilmTransactionRecord
     */
    public FilmTransactionRecord(String filmTransactionId, String filmId, String customerId, Integer numDays, String action, Timestamp createdOn) {
        super(FilmTransaction.FILM_TRANSACTION);

        set(0, filmTransactionId);
        set(1, filmId);
        set(2, customerId);
        set(3, numDays);
        set(4, action);
        set(5, createdOn);
    }
}
